### PR TITLE
Add certificates backup in case of test failure

### PR DESCRIPTION
**Pull request by sivanov-nuodb**
**Changes**
- backup generated certificates in case of test failure so that they could be used to reproduce the problem

**Why**
- Requested by @vegichan by one of his comments in https://github.com/nuodb/nuodb-helm-charts/pull/11

**Testing Performed**
- Local automation tests with minikube

### CODE REVIEW

**Comment by vegichan** [comment]
if travis fails, you wont be able to find the certificates. We dont have access to disk.

You have to either save them to some S3 artifact storage, or print the content to stdout.

**Comment by sivanov-nuodb** [comment]
> if travis fails, you wont be able to find the certificates. We dont have access to disk.
> 
> You have to either save them to some S3 artifact storage, or print the content to stdout.

@vegichan printing the certificate sounds like a reasonable solution. Do you have some specific nuocmd command in mind?

**Comment by vegichan** [comment]
hmm. good question. I am not aware of any nuocmd command that will give you all the data you need and exists in all 4.0 releases. I think that we added something in master.

Just `cat` them to stdout? Or read the files and `os.Stdout` :)

`GetAppLog` already has the logs in memory, so it is easy to just write them to stdout if the test failed and the env variable is set (`shouldPrintToStdout()`)

**Comment by sivanov-nuodb** [comment]
> hmm. good question. I am not aware of any nuocmd command that will give you all the data you need and exists in all 4.0 releases. I think that we added something in master.
> 
> Just `cat` them to stdout? Or read the files and `os.Stdout` :)
> 
> `GetAppLog` already has the logs in memory, so it is easy to just write them to stdout if the test failed and the env variable is set (`shouldPrintToStdout()`)

@vegichan The problem with just cat-ing them is that they are binary files and will be displayed as wired symbols in the stdout. Instead, I decided to use `hexdump` and print the files in hex.
Example output:
```
--- FAIL: TestKubernetesTLSRotation (56.12s)
    tls.go:101: Certificate files location: /tmp/tls-keys630560078
    tls.go:69: Found generated certificate file: ca.cert
    tls.go:69: Found generated certificate file: ca.p12
    tls.go:69: Found generated certificate file: nuoadmin-truststore.p12
    tls.go:69: Found generated certificate file: nuoadmin.p12
    tls.go:69: Found generated certificate file: nuocmd.p12
    tls.go:69: Found generated certificate file: nuocmd.pem
    minikube_tls_rotation_test.go:52: 
    tls.go:112: Printing certificate files in /tmp/tls-keys630560078.
    tls.go:115: ca.cert:
        2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49
        46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 44
        ...                     
    tls.go:115: ca.p12:
        30 82 0a 03 02 01 03 30 82 09 bc 06 09 2a 86 48
        86 f7 0d 01 07 01 a0 82 09 ad 04 82 09 a9 30 82
        ...                           
    tls.go:115: nuoadmin-truststore.p12:
        30 82 08 5e 02 01 03 30 82 08 17 06 09 2a 86 48
        86 f7 0d 01 07 01 a0 82 08 08 04 82 08 04 30 82
        ...                                          
    tls.go:115: nuoadmin.p12:
        30 82 0e 57 02 01 03 30 82 0e 10 06 09 2a 86 48
        86 f7 0d 01 07 01 a0 82 0e 01 04 82 0d fd 30 82
        ...               
    tls.go:115: nuocmd.p12:
        30 82 0a 0b 02 01 03 30 82 09 c4 06 09 2a 86 48
        86 f7 0d 01 07 01 a0 82 09 b5 04 82 09 b1 30 82
        ...   
    tls.go:115: nuocmd.pem:
        2d 2d 2d 2d 2d 42 45 47 49 4e 20 50 52 49 56 41
        54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45
        76 67 49 42 41 44 41 4e 42 67 6b 71 68 6b 69 47
        ...
```
Afterwards one could use `xxd -r -p ~/a.hex a.bin` to recreate the original file if needed.

**Pull request merged**
